test_mysql2: &test_mysql2
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

test_pg: &test_pg
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost
  encoding: utf8

development:
  database: nocms-menus-dev
  <<: *test_<%= NoCms::Menus.installed_db_gem %>

test:
  database: nocms_menus_test
  <<: *test_<%= NoCms::Menus.installed_db_gem %>
